// Code generated by ObjectBox; DO NOT EDIT.

package schema

import (
	"github.com/objectbox/objectbox-go/objectbox"
)

// ObjectBoxModel declares and builds the model from all the entities in the package.
// It is usually used when setting-up ObjectBox as an argument to the Builder.Model() function.
func ObjectBoxModel() *objectbox.Model {
	model := objectbox.NewModel()
	model.GeneratorVersion(6)

	model.RegisterBinding(CardBinding)
	model.RegisterBinding(DraftBinding)
	model.RegisterBinding(PackBinding)
	model.RegisterBinding(SeatBinding)
	model.RegisterBinding(UserBinding)
	model.RegisterBinding(EventBinding)
	model.RegisterBinding(SkipBinding)
	model.LastEntityId(7, 582453211065114336)
	model.LastIndexId(9, 5789332885209914495)
	model.LastRelationId(9, 6610520635914740722)

	return model
}
