// Code generated by ObjectBox; DO NOT EDIT.

package schema

import (
	"github.com/objectbox/objectbox-go/objectbox"
)

// ObjectBoxModel declares and builds the model from all the entities in the package.
// It is usually used when setting-up ObjectBox as an argument to the Builder.Model() function.
func ObjectBoxModel() *objectbox.Model {
	model := objectbox.NewModel()
	model.GeneratorVersion(6)

	model.RegisterBinding(CardBinding)
	model.RegisterBinding(DraftBinding)
	model.RegisterBinding(PackBinding)
	model.RegisterBinding(SeatBinding)
	model.RegisterBinding(UserBinding)
	model.RegisterBinding(EventBinding)
	model.LastEntityId(6, 7673531568455826754)
	model.LastIndexId(6, 9101246984390296186)
	model.LastRelationId(8, 3916323228265520547)

	return model
}
